CREATE TABLE "genres" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL
);

CREATE TABLE "mpa_ratings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rating" VARCHAR(10) NOT NULL
);

CREATE TABLE "films" (
  "film_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "description" TEXT NOT NULL,
  "release_date" DATE NOT NULL,
  "duration" INT NOT NULL,
  "mpa_rating_id" BIGINT NOT NULL
);

CREATE TABLE "film_genres" (
  "film_id" BIGINT,
  "genre_id" BIGINT,
  "PRIMARY" KEY(film_id,genre_id)
);

CREATE TABLE "users" (
  "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" VARCHAR(255) UNIQUE NOT NULL,
  "login" VARCHAR(255) UNIQUE NOT NULL,
  "name" VARCHAR(255) NOT NULL,
  "birthday" DATE NOT NULL
);

CREATE TABLE "film_likes" (
  "film_id" BIGINT,
  "user_id" BIGINT,
  "PRIMARY" KEY(film_id,user_id)
);

CREATE TABLE "friendships" (
  "user_id" BIGINT,
  "friend_id" BIGINT,
  "status" BOOLEAN NOT NULL,
  "PRIMARY" KEY(user_id,friend_id)
);

ALTER TABLE "film_genres" ADD FOREIGN KEY ("film_id") REFERENCES "films" ("film_id");

ALTER TABLE "film_genres" ADD FOREIGN KEY ("genre_id") REFERENCES "genres" ("id");

ALTER TABLE "film_likes" ADD FOREIGN KEY ("film_id") REFERENCES "films" ("film_id");

ALTER TABLE "film_likes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "friendships" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "friendships" ADD FOREIGN KEY ("friend_id") REFERENCES "users" ("user_id");
